import type {
  SparklineConfig,
  SparklineCharacterSet,
  ASCIIArtConfig,
  WebhookPayload,
  WebhookResponse,
  WebhookConfig,
  ValidationError,
  WebhookError,
  NumericArray,
  WebhookSendResult,
  SparklineGenerationResult,
  ConfigFile,
  DiscordEmbed,
  SlackBlock,
  HttpMethod,
  HttpRequestOptions,
  WebhookProvider,
  TelegramConfig,
  GaugeOptions,
  StatsOptions,
  StatsResult,
  ThresholdConfig,
  SparkStatusResult,
  DashboardMetric,
  DashboardOptions,
} from "./types.js";
import { generateSparkline, generateSparklineWithOutliers, generateASCIIArt, spark, barChart, trend, gauge, stats, sparkWithStatus, dashboard } from "./sparkline.js";
import { sendWebhook } from "./webhook.js";
import { isNumericArray, isSparklineConfig, isWebhookConfig } from "./types.js";

export {
  generateSparkline,
  generateSparklineWithOutliers,
  generateASCIIArt,
  spark,
  barChart,
  trend,
  gauge,
  stats,
  sparkWithStatus,
  dashboard,
  sendWebhook,
  isNumericArray,
  isSparklineConfig,
  isWebhookConfig,
};
export type {
  SparklineConfig,
  SparklineCharacterSet,
  ASCIIArtConfig,
  WebhookPayload,
  WebhookResponse,
  WebhookConfig,
  ValidationError,
  WebhookError,
  NumericArray,
  WebhookSendResult,
  SparklineGenerationResult,
  ConfigFile,
  DiscordEmbed,
  SlackBlock,
  HttpMethod,
  HttpRequestOptions,
  WebhookProvider,
  TelegramConfig,
  GaugeOptions,
  StatsOptions,
  StatsResult,
  ThresholdConfig,
  SparkStatusResult,
  DashboardMetric,
  DashboardOptions,
};